<?php
class FormEdit{
  const BASE_URL = 'http://localhost/web2/tp2/';
function showFormEdit($item){
 $itemS = $item[0];
 ?>
  <!DOCTYPE html>


  <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>
    
  </body>
  </html>


  <form class="mb-3" action="<?= BASE_URL ?>edit/<?php echo $itemS['id']?>" method="post">
          
              <input  id="nombreE" name="nombreE" placeholder="nombre">
              <input  id="apellidoE" name="apellidoE" placeholder="apellido">
              <input  id="nombre_productoE" name="nombre_productoE" placeholder="nombre del producto">
              <input  id="tipoDeCompraE" name="tipoDeCompraE" placeholder="tipoDeCompra">

              <button type="submit" class="btn btn-primary">editar</button>
  </form>
  <?php
  }
}