<?php require 'C:\xampp\htdocs\web2\tp2/templates/header.phtml' ?>

<?php if ($error): ?>
    <div class='alert alert-danger' role='alert'>
        <?= $error ?>
    </div>
<?php endif ?>

<form method='post' action='listar'>
    <div class='form-group'>
        <label for='email'>Email</label>
        <input type='email' class='form-control' id='email' name='email' required>
    </div>
    <div class='form-group'>
        <label for='password'>Password</label>
        <input type='password' class='form-control' id='password' name='password' required>
    </div>
    <button type='submit' class='btn btn-primary'>Login</button>
</form>

<?php require 'C:\xampp\htdocs\web2\tp2/templates/footer.phtml' ?>
